
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author luisg_000
 */
public class FazPedido extends javax.swing.JFrame {
    
    
    /**
     * Creates new form FazPedido
     */
    public FazPedido() {
        initComponents();
        if(Principal.pedidoImediato.getId() != 0){
            
            campoIdFornecedor.setText(String.valueOf(Principal.pedidoImediato.getIdFornecedor()));
            botaoListarProdutosFornecedor.doClick();
            campoIdProdutoFornecedor.setText(String.valueOf(Principal.pedidoImediato.getId()));
            botaoPreencherCampos.doClick();
            campoNomeProduto.setText(Principal.pedidoImediato.getNomeProduto());
            campoMarcaProduto.setText(Principal.pedidoImediato.getMarcaProduto());
            campoQuantidadeMinima.setText("já cadastrado");
            campoQuantidadeMinima.setEditable(false);
            campoPrecoMedia.setText(String.valueOf(Principal.pedidoImediato.getPrecoProduto()));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoIdFornecedor = new javax.swing.JTextField();
        botaoListarProdutosFornecedor = new javax.swing.JButton();
        campoNomeFornecedor = new javax.swing.JTextField();
        campoIdProdutoFornecedor = new javax.swing.JTextField();
        botaoPreencherCampos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutoFornecedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        campoMarcaProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoPrecoMedia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoQuantidadeMinima = new javax.swing.JTextField();
        botaoLimpar = new javax.swing.JButton();
        botaoFazerPedido = new javax.swing.JButton();
        botaoMenuAnterior = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel6.setText("Código Fornecedor:");

        jLabel8.setText("Fornecedor:");

        jLabel7.setText("Código Produto Fornecedor:");

        botaoListarProdutosFornecedor.setText("Listar Produtos do Fornecedor");
        botaoListarProdutosFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoListarProdutosFornecedorActionPerformed(evt);
            }
        });

        campoNomeFornecedor.setEditable(false);

        botaoPreencherCampos.setText("Preencher Campos");
        botaoPreencherCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPreencherCamposActionPerformed(evt);
            }
        });

        tabelaProdutoFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Marca", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutoFornecedor);

        jLabel1.setText("Nome do Protuto:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Quantidade:");

        jLabel4.setText("Preço:");

        jLabel5.setText("Quantidade Mínima:");

        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoFazerPedido.setText("Fazer Pedido");
        botaoFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFazerPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(71, 71, 71)
                        .addComponent(campoIdFornecedor)
                        .addGap(18, 18, 18)
                        .addComponent(botaoListarProdutosFornecedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoNomeFornecedor)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(campoIdProdutoFornecedor)
                                .addGap(18, 18, 18)
                                .addComponent(botaoPreencherCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoPrecoMedia)
                            .addComponent(campoQuantidade)
                            .addComponent(campoMarcaProduto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(campoQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoFazerPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoIdFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoListarProdutosFornecedor))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(campoNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(campoIdProdutoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoPreencherCampos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(campoMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoPrecoMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoQuantidadeMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoFazerPedido)
                            .addComponent(botaoLimpar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        botaoMenuAnterior.setText("Menu Anterior");
        botaoMenuAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoMenuAnteriorActionPerformed(evt);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoMenuAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoMenuAnterior)
                    .addComponent(botaoSair))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoNomeProduto.setText("");
        campoMarcaProduto.setText("");
        campoQuantidade.setText("");
        campoQuantidadeMinima.setText("");
        campoPrecoMedia.setText("");

    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFazerPedidoActionPerformed
        if(campoQuantidadeMinima.getText().equals("já cadastrado")){
           int idPrCliente = Principal.produto.getId();
            int idFornecedor = Integer.parseInt(campoIdFornecedor.getText());
            Date date  = new Date();    
            Calendar c = Calendar.getInstance();
            c.setTime(date);
            int dia = c.get(Calendar.DATE);
            int mes = c.get(Calendar.MONTH);
            int ano = c.get(Calendar.YEAR);
            String dataCompleta = String.valueOf(ano)+"-"+String.valueOf(mes)+"-"+String.valueOf(dia);
            int quantComprada = Integer.parseInt(campoQuantidade.getText());
            int quantidadeEstoque = Principal.produto.getQuantidade();
            int quantidadeTotal = quantidadeEstoque + quantComprada;
            double preco = Double.parseDouble(campoPrecoMedia.getText());
            double valorCompra = preco * quantComprada;
            double valorTotal = quantidadeTotal * preco; 
            
            Conexao.cadastraPedido(idPrCliente,idFornecedor,dataCompleta,preco,quantComprada,valorCompra);
            
            Conexao.adicionaEstoque(idPrCliente,quantidadeTotal,preco,valorTotal);
            Conexao.iniciarVariaveisProdutoEstoque();
            
            Principal.pedidoImediato = new Fornecedor(0,"","","").new ProdutoFornecedor(0,0, "", "", 0);
            botaoLimpar.doClick();
            
            campoQuantidadeMinima.setEditable(true);
            
            
        }else{
            int idFornecedor = Integer.parseInt(campoIdFornecedor.getText());
            String nomeProduto = campoNomeProduto.getText();
            String marcaProduto = campoMarcaProduto.getText();
            int quantidade = Integer.parseInt(campoQuantidade.getText());
            int quantMinima = Integer.parseInt(campoQuantidadeMinima.getText());
            double precoMedia = Double.parseDouble(campoPrecoMedia.getText());
            double valorTotal = quantidade * precoMedia;
            
            int id = Conexao.cadastraProdutoEstoque(nomeProduto,marcaProduto,
            quantidade,quantMinima,precoMedia,valorTotal);
            
            Conexao.iniciarVariaveisProdutoEstoque();
            
            Date date  = new Date();    
            Calendar c = Calendar.getInstance();
            c.setTime(date);
            int dia = c.get(Calendar.DATE);
            int mes = c.get(Calendar.MONTH);
            int ano = c.get(Calendar.YEAR);
            String dataCompleta = String.valueOf(ano)+"-"+String.valueOf(mes)+"-"+String.valueOf(dia);
            
            Conexao.cadastraPedido(id,idFornecedor,dataCompleta,precoMedia,quantidade,valorTotal);
            
            botaoLimpar.doClick();
            campoQuantidadeMinima.setEditable(true);
        }
        
 

       

    }//GEN-LAST:event_botaoFazerPedidoActionPerformed

    private void botaoMenuAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoMenuAnteriorActionPerformed
        this.dispose(); new Principal().setVisible(true);
    }//GEN-LAST:event_botaoMenuAnteriorActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoPreencherCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPreencherCamposActionPerformed
        int idProdutoFornecedor = Integer.parseInt(campoIdProdutoFornecedor.getText());
        
        boolean checkProdutoCadastradoEstoque = false;
        
        for(Fornecedor.ProdutoFornecedor x: Principal.produtosFornecedor){
            if(idProdutoFornecedor==x.getId()){
                Principal.produtoFornecedor = x;
            }
        }

        for(ProdutoEstoque x: Principal.produtosEstoque){
            if(Principal.produtoFornecedor.getNomeProduto().equals(x.getNomeProduto()) && Principal.produtoFornecedor.getMarcaProduto().equals(x.getMarcaProduto())){
                Principal.produto = x;
                campoNomeProduto.setText(x.getNomeProduto());
                campoMarcaProduto.setText(x.getMarcaProduto());
                campoPrecoMedia.setText(String.valueOf(x.getPrecoMedia()));
                campoQuantidadeMinima.setText("já cadastrado");
                campoQuantidadeMinima.setEditable(false);
                checkProdutoCadastradoEstoque = true;
            }   
        }
        if(checkProdutoCadastradoEstoque==false){
                campoNomeProduto.setText(Principal.produtoFornecedor.getNomeProduto());
                campoMarcaProduto.setText(Principal.produtoFornecedor.getMarcaProduto());
                campoPrecoMedia.setText(String.valueOf(Principal.produtoFornecedor.getPrecoProduto()));
            }

    }//GEN-LAST:event_botaoPreencherCamposActionPerformed

    private void botaoListarProdutosFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoListarProdutosFornecedorActionPerformed
        int idFornecedor = Integer.parseInt(campoIdFornecedor.getText());
        for(Fornecedor x: Principal.fornecedores){
            if(idFornecedor==x.getId()){
                campoNomeFornecedor.setText(x.getNomeFornecedor());
            }

        }

        Conexao.iniciarVariaveisProdutoFornecedor();
        boolean checkId = false;
        DefaultTableModel val = (DefaultTableModel) tabelaProdutoFornecedor.getModel();
        val.setNumRows(0);
        for(Fornecedor.ProdutoFornecedor x:Principal.produtosFornecedor){
            if(idFornecedor == x.getIdFornecedor()){
                val.addRow(new String[]{String.valueOf(x.getId()),x.getNomeProduto(),x.getMarcaProduto(),
                    String.valueOf(x.getPrecoProduto())});checkId = true;
        }
        }
        if(checkId==false){
            JOptionPane.showMessageDialog(null, "Código Inexistente;");
        }
    }//GEN-LAST:event_botaoListarProdutosFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFazerPedido;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoListarProdutosFornecedor;
    private javax.swing.JButton botaoMenuAnterior;
    private javax.swing.JButton botaoPreencherCampos;
    private javax.swing.JButton botaoSair;
    private javax.swing.JTextField campoIdFornecedor;
    private javax.swing.JTextField campoIdProdutoFornecedor;
    private javax.swing.JTextField campoMarcaProduto;
    private javax.swing.JTextField campoNomeFornecedor;
    private javax.swing.JTextField campoNomeProduto;
    private javax.swing.JTextField campoPrecoMedia;
    private javax.swing.JTextField campoQuantidade;
    private javax.swing.JTextField campoQuantidadeMinima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProdutoFornecedor;
    // End of variables declaration//GEN-END:variables
}
